# -*- coding: utf-8 -*-
"""aula3_ltp_I_2022.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-JJrLX_WZmZBCyr95ThpZSESOIF2Iabk
"""

peso = 200
altura = 1.80
imc = peso / (altura * altura)
print(imc)
if imc < 18.5:
  print('Abaixo do peso')
elif imc >= 18.5 and imc < 24.9:
  print('Peso normal')
elif imc >= 24.9 and imc < 29.9:
  print('sobrepeso')
elif imc >=29.9 and imc < 34.9:
  print('obesidade grau I')
elif imc >=34.9 and imc < 39.9:
  print('obesidade grau II')
else:
  print('obesidade grau III ou morbida')

lst = []
type(lst)
lst.append(1)
lst.append(1.6)
lst.append('UGB')
lst.append(True)
lst.append([4,6,8])
print(lst)
lst[4]
lst[4][2]
lista = [6, 5, 8, 3]
print(lst, lista)
lst.extend(lista)
print(lst)
lst.index('UGB')
lst.insert(1, 'andre')
lst.pop(4)
print(lst)
lst.reverse()
b = lista.sort()
print(b)

a = (1, 9, 3)

type(a)
a[1]
b = list(a)
c = tuple(b)
d = 'andre ricardo'
list(d)
d[1]
# b = 1.4
# for i in b:
#   print(i)

dicio = {'nome': 'andre', 'end': 'ugb'}
dicio.keys()
dicio.values()
# for i in dicio:
#   print(dicio[i])
dicio['rua'] = 'Vereador Aristides Martins'
for k, v in dicio.items():
  print (k, v)
print(dicio)

conjunto = set()
# conjunto = {}
type(conjunto)
lista1 = [6, 5, 8, 3, 6]
lista2 = [4, 5, 9, 3, 6]
a = set(lista1)
b = set(lista2)
print(a)
print(b)
print(a.union(b))
print(a.intersection(b))
print(a.difference(b))

a = 1
while True:
  if a == 7000000:
    print(a)
    break
  a = a + 1 # a += 1

a = 0
b = 0
while a < 10:
  a += 1
  if b >= 5:
    continue
  b += 1
print(a, b)

sair = 'nao'
while sair == 'nao':
  a = int(input('Entre com o valor de A: '))
  b = int(input('Entre com o valor de B: '))
  c = int(input('Entre com o valor de C: '))

  if a == b and b == c:
    print('equilátero')
  elif a == b or a == c or b == c:
    print('isósceles')
  else:
    print('qualquer')

  sair = input('Quer sair? ')