# -*- coding: utf-8 -*-
"""aula_2_2022_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12YYZEwUaF0O89CF4z7EUOpUAUtPXY3yt

A fórmula para calcular a área de uma circunferência é: area = π . raio2. Considerando para este problema que π = 3.14159:

- Efetue o cálculo da área, elevando o valor de raio ao quadrado e multiplicando por π.

Entrada
A entrada contém um valor de ponto flutuante (dupla precisão), no caso, a variável raio.

Saída
Apresentar a mensagem "A=" seguido pelo valor da variável area, conforme exemplo abaixo, com 4 casas após o ponto decimal. Utilize variáveis de dupla precisão (double). Como todos os problemas, não esqueça de imprimir o fim de linha após o resultado, caso contrário, você receberá "Presentation Error".
"""

raio = float(input('Entre com o raio: '))
p = 3.14159

a = p * raio**2
# print('%d' % a)
print(f'{a:.4f}')

a = int(input('Entre com o valor de A: '))
b = int(input('Entre com o valor de B: '))
soma = a + b
print(soma)

def entre_zero_dez(nota):
  while True:
    valor = float(input(f"entre com a nota {nota}: "))
    if valor < 0 or valor > 10:
      print('Valores entre 0 e 10')
      continue
    else:
      return valor

# while True:
#   nota2 = float(input("entre com a nota 2: "))
#   if nota2 < 0 or nota2 > 10:
#     print('Valores entre 0 e 10')
#     continue
#   else:
#     break

nota1 = entre_zero_dez(1)
nota2 = entre_zero_dez(2)

media = ((nota1 * 3.5) + (nota2 * 7.5))/11

print(f'MEDIA = {media:.5f}')

a = 1
if a == 2:
  pass